sources:
  - file: Igolchatye-podshipniki-SKF-сжатый-сжатый.pdf
    purpose: catalog
    status: unverified
  - file: Igolchatye-podshipniki-SKF.pdf
    purpose: catalog
    status: unverified
  - file: Katalog-Besshponochnye-Vtulki-FX-SKF.pdf
    purpose: catalog
    status: unverified
  - file: Katalog-SKF-Pretsizionnye-Relsovye-Napravlyayushchie.pdf
    purpose: catalog
    status: unverified
  - file: Katalog-SKF-Profilnye-Lineynye-Napravlyayushchie.pdf
    purpose: catalog
    status: unverified
  - file: Katalog-SKF-Promyshlennye-Uplotneniya-dlya-Valov.-Katalog-v-PDF..pdf
    purpose: catalog
    status: unverified
  - file: Katalog-Silovye-Privodnye-Remni-SKF.pdf
    purpose: catalog
    status: unverified
  - file: Katalog-Uplotnyennye-sfericheskie-rolikopodshipniki-SKF-Explorer.pdf
    purpose: catalog
    status: unverified
  - file: Kompozitnye-podshipniki-skolzheniya-SKF.pdf
    purpose: catalog
    status: unverified
  - file: Korpusa-podshipnikov-SKF.pdf
    purpose: catalog
    status: unverified
  - file: Obshchii_-katalog-podshipnikov-SKF.pdf
    purpose: catalog
    status: unverified
  - file: Подшипники SKF.docx
    purpose: catalog
    status: unverified
