sources:
  - file: Induktsionnye_nagrevateli_podshipnikov_Schaeffler_HEATER-сжатый-сжатый.pdf
    purpose: catalog
    status: unverified
  - file: Induktsionnye_nagrevateli_podshipnikov_Schaeffler_HEATER.pdf
    purpose: catalog
    status: unverified
  - file: Karmannyy-spravochnik-po-tekhnicheskomu-obsluzhivaniyu-podshipnikov-ot-NSk.pdf
    purpose: catalog
    status: unverified
  - file: Katalog-instrumentov-dlya-montazha-podshipnikov-NSK.pdf
    purpose: catalog
    status: unverified
  - file: Lineynye-napravlyayushchie-NSK-serii-NH_-NS.pdf
    purpose: catalog
    status: unverified
  - file: Metallopolimernye_podshipniki_skolzheniya_INA.pdf
    purpose: catalog
    status: unverified
  - file: Oboznacheniya-podshipnikov-NSK.pdf
    purpose: catalog
    status: unverified
  - file: Obshchiy-katalog-podshipnikov-FAG-chast-1.pdf
    purpose: catalog
    status: unverified
  - file: Obshchiy-katalog-podshipnikov-FAG-chast-2.pdf
    purpose: catalog
    status: unverified
  - file: Obshchiy-katalog-podshipnikov-FAG-chast-3.pdf
    purpose: catalog
    status: unverified
  - file: Obshchiy-katalog-podshipnikov-kacheniya-NSK.pdf
    purpose: catalog
    status: unverified
  - file: Obshchiy_Katalog_s_oboznacheniyami_podshipnikov_SCHAEFFLER.pdf
    purpose: catalog
    status: unverified
  - file: Odnoryadnye-radialnye-sharikopodshipniki-FAG-pokoleniya-S.pdf
    purpose: catalog
    status: unverified
  - file: Podshipniki-dlya-bumagodelatelnykh-mashin-ot-NSK.pdf
    purpose: catalog
    status: unverified
  - file: Podshipniki-dlya-gornodobyvayushchey-promyshlennosti-NSK.pdf
    purpose: catalog
    status: unverified
  - file: Podshipniki-dlya-gornodobyvayushchey-promyshlennosti.-Podshipniki-dlya-gornogo-promyshlennogo-oborudovaniya.pdf
    purpose: catalog
    status: unverified
  - file: Podshipniki-dlya-metallurgicheskoy-promyshlennosti-NSK.pdf
    purpose: catalog
    status: unverified
  - file: Podshipniki-dlya-nasosov-i-kompressorov-ot-NSK.pdf
    purpose: catalog
    status: unverified
  - file: Podshipniki_-kacheniya_i_uslugi-dlya_gornodobyvayushchego_i_gorno_obogatitelnogo_oborudovaniya_SCHAEFFLER.pdf
    purpose: catalog
    status: unverified
  - file: Podshipniki_roliki_Opornye_roliki_INA.pdf
    purpose: catalog
    status: unverified
